import {
  Search,
  Briefcase,
  User,
  Users,
  ShieldCheck,
  Shield,
  ShieldUser,
  Heart,
  HeartHandshake,
  HeartPulse,
  Building2,
  Bell,
  FileText,
  FileCheck,
  FilePlus,
  FileUser,
  Rocket,
  TrendingUp,
  Quote,
  Star,
  MapPin,
  Phone,
  Mail,
  Menu,
  X,
  Clock,
  LayoutGrid,
  Headphones,
  Send,
  Lock,
  Globe,
  CircleHelp,
  MessageCircle,
  Tag,
  Check,
  UserCheck,
  Stethoscope,
  ChefHat,
  Bed,
  Utensils,
  CircleCheck,
  Target,
  Zap,
  Megaphone,
  FilePen,
  ArrowRight,
} from "lucide-react";
import { GiMapleLeaf } from "react-icons/gi";

/** String keys used in data files map to icon components. */
export const icons = {
  search: Search,
  briefcase: Briefcase,
  user: User,
  users: Users,
  shieldCheck: ShieldCheck,
  shield: Shield,
  heart: Heart,
  heartHandshake: HeartHandshake,
  building2: Building2,
  bell: Bell,
  fileText: FileText,
  fileCheck: FileCheck,
  rocket: Rocket,
  trendingUp: TrendingUp,
  quote: Quote,
  star: Star,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  menu: Menu,
  close: X,
  clock: Clock,
  layoutGrid: LayoutGrid,
  mapleLeaf: GiMapleLeaf,
  headphones: Headphones,
  send: Send,
  lock: Lock,
  globe: Globe,
  helpCircle: CircleHelp,
  messageCircle: MessageCircle,
  tag: Tag,
  check: Check,
  circleCheck: CircleCheck,
  shieldUser: ShieldUser,
  filePlus: FilePlus,
  fileUser: FileUser,
  userCheck: UserCheck,
  stethoscope: Stethoscope,
  chefHat: ChefHat,
  bed: Bed,
  utensils: Utensils,
  heartPulse: HeartPulse,
  target: Target,
  zap: Zap,
  megaphone: Megaphone,
  filePen: FilePen,
  arrowRight: ArrowRight,
};

export function getIcon(name) {
  return icons[name] || Users;
}
